/*
 * generated by Xtext 2.16.0
 */
package org.xtext.mixin.fanfan


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class MixfanfStandaloneSetup extends MixfanfStandaloneSetupGenerated {

	def static void doSetup() {
		new MixfanfStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
